### ISSUE TITLE
View parameter 'appbar' not working

### ISSUE THREAD

**Issue by Endogen** [saurabhwadekar/flet_route#8]
When i create an `AppBar` and want to add it to the `View` then i need to add it to the `controls` list. In `View` there is the parameter `appbar` but when i assign my `AppBar` to that then it won't show up.

This does not work:
```python
        ft.View(
            appbar=appbar
        )
```

This does work:
```python
        ft.View(
            controls=[
                appbar
            ]
        )
```

**Comment by VordyV** [comment]
As it turned out, the developer made the appbar common to the entire app. The appbar is specified in Routing(appbar=ft.AppBar()).
The Appbar is not displayed on the error page, it is not added there.
This approach is not always suitable, for example, the appbar is not suitable for the login or reg page.
